auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: xdite
    # url:  http://blog.xdite.net
    company:
        name: Rocodev
        # url:  http://rocodev.com/

fork_url: https://github.com/shower/shower
progress: true
